def get_tax_variables_2021(tax_data):
    variables = {
        "N37": int(tax_data["F8995 QUALIFIED BUSINESS INCOME DEDUCTION COMPUTER"]),
        "N38": int(tax_data["SELF EMPLOYMENT TAX DEDUCTION PER COMPUTER"]),
        "N39": int(tax_data["ADJUSTED GROSS INCOME"]),
        "N40": int(tax_data["ADJUSTED GROSS INCOME PER COMPUTER"]),
        "N41": int(tax_data["STANDARD DEDUCTION PER COMPUTER"]),
        "N42": int(tax_data["TENTATIVE TAX"]),
        "N43": int(tax_data["TOTAL CREDITS"]),
        "N44": int(tax_data["SE TAX"]),
        "N45": int(tax_data["FEDERAL INCOME TAX WITHHELD"]),
        "N46": int(tax_data["ESTIMATED TAX PAYMENTS"]),
        "N47": int(tax_data["OTHER PAYMENT CREDIT"]),
        "N48": int(tax_data["EARNED INCOME CREDIT"]),
        "N49": int(tax_data["TOTAL PAYMENTS"]),
        "N50": int(tax_data["BAL DUE/OVER PYMT USING TP FIG PER COMPUTER"]),
        "N51": int(tax_data["TOTAL QUALIFIED BUSINESS INCOME OR LOSS"]),
        "N52": tax_data["FILING STATUS"],
        "N53": int(tax_data["SE INCOME PER COMPUTER"]),
        "N54": int(tax_data["Credit to your account"]),
        "N55": int(tax_data["ACCOUNT BALANCE"]),
        "N56": int(tax_data["ACCRUED INTEREST"]),
        "N57": int(tax_data["TAXABLE INCOME"]),
        "N58": int(tax_data["TAX PER RETURN"]),
        "N59": int(tax_data["SCHEDULE 8812 ADDITIONAL CHILD TAX CREDIT"]),
        "N60": int(tax_data["FORM 2439 REGULATED INVESTMENT COMPANY CREDIT1"]),
        "N61": int(tax_data["FORM 4136 CREDIT FOR FEDERAL TAX ON FUELS PER COMPUTER1"]),
        "N62": int(tax_data["TOTAL EDUCATION CREDIT AMOUNT PER COMPUTER"]),
        "N63": int(tax_data["HEALTH COVERAGE TX CR"]),
        "N64": int(tax_data["AMOUNT YOU OWE"]),
        "N65": int(tax_data["REFUND AMOUNT"]),
        "N66": int(tax_data["SICK FAMILY LEAVE CREDIT AFTER 3-31-21"]),
        "N67": int(tax_data["SICK FAMILY LEAVE CREDIT"]),
        "N68": int(tax_data["PREMIUM TAX CREDIT AMOUNT"]),
        "N69": int(tax_data["REFUNDABLE CREDITS PER COMPUTER"]),
        "N70": int(tax_data["SCHEDULE 8812 ADDITIONAL CHILD TAX CREDIT PER COMPUTER1"]),
        "N71": int(tax_data["RECOVERY REBATE CREDIT PER COMPUTER"]),
        "N72": int(tax_data["WAGES, SALARIES, TIPS, ETC"]),
        "N73": int(tax_data["TAX-EXEMPT INTEREST"]),
        "N74": int(tax_data["QUALIFIED DIVIDENDS"]),
        "N75": int(tax_data["TOTAL IRA DISTRIBUTIONS"]),
        "N76": int(tax_data["TOTAL PENSIONS AND ANNUITIES"]),
        "N77": int(tax_data["TOTAL SOCIAL SECURITY BENEFITS"]),
        "N78": int(tax_data["TAXABLE INTEREST INCOME"]),
        "N79": int(tax_data["ORDINARY DIVIDEND INCOME"]),
        "N80": int(tax_data["TAXABLE IRA DISTRIBUTIONS"]),
        "N81": int(tax_data["TAXABLE PENSION/ANNUITY AMOUNT"]),
        "N82": int(tax_data["TAXABLE SOCIAL SECURITY BENEFITS PER COMPUTER"]),
        "N83": int(tax_data["CAPITAL GAIN OR LOSS"]),
        "N84": int(tax_data["OTHER INCOME"]),
        "N85": int(tax_data["TOTAL ADJUSTMENTS PER COMPUTER"]),
        "N86": int(tax_data["NON ITEMIZED CHARITABLE CONTRIBUTION PER COMPUTER"]),
        "N87": int(tax_data["BUSINESS INCOME OR LOSS (SCHEDULE C)"]),
        "N88": int(tax_data["CHILD AND OTHER DEPENDENT CREDIT PER COMPUTER"]),
        "N89": int(tax_data["EXCESS ADVANCE PREMIUM TAX CREDIT REPAYMENT AMOUNT"]),
        "N90": int(tax_data["SEC 965 TAX INSTALLMENT"]),
        "N91": int(tax_data["CHILD & DEPENDENT CARE CREDIT"]),
        "N92": int(tax_data["ESTIMATED TAX PENALTY"]),
        "N93": int(tax_data["APPLIED TO NEXT YEAR'S ESTIMATED TAX"]),
        "N94": int(tax_data["EARNED INCOME CREDIT NONTAXABLE COMBAT PAY"]),
        "N95": int(tax_data["MAX DEFERRED TAX PER COMPUTER"]),
        "N96": int(tax_data["EIC PRIOR YEAR EARNED INCOME"]),
        "N97": int(tax_data["FOREIGN TAX CREDIT PER COMPUTER"]),
        "N98": int(tax_data["EDUCATION CREDIT PER COMPUTER"]),
        "N99": int(tax_data["RETIREMENT SAVINGS CNTRB CREDIT PER COMPUTER"]),
        "N100": int(tax_data["RESIDENTIAL CLEAN ENERGY CREDIT PER COMPUTER"]),
        "N101": int(tax_data["F3800, F8801 AND OTHER CREDIT AMOUNT"]),
        "N102": int(tax_data["AMOUNT PAID WITH FORM 4868"]),
        "N103": int(tax_data["EXCESS SOCIAL SECURITY & RRTA TAX WITHHELD"]),
        "N104": int(tax_data["ADDITIONAL INCOME PER COMPUTER"]),
        "N105": int(tax_data["TOTAL INCOME PER COMPUTER"]),
        "N106": int(tax_data["ADDITIONAL STANDARD DEDUCTION PER COMPUTER"]),
        "N107": int(tax_data["TAXABLE INCOME PER COMPUTER"]),
        "N108": int(tax_data["FORM 6251 ALTERNATIVE MINIMUM TAX PER COMPUTER"]),
        "N109": int(tax_data["EXCESS ADVANCE PREMIUM TAX CREDIT REPAYMENT AMOUNT"]),
        "N110": int(tax_data["TOTAL OTHER TAXES PER COMPUTER"]),
        "N111": int(tax_data["TAXABLE INTEREST INCOME"]),
        "N112": int(tax_data["ORDINARY DIVIDEND INCOME"]),
        "N113": int(tax_data["CAPITAL GAINS OR LOSS"]),
        "N114": int(tax_data["TENTATIVE TAX PER COMPUTER"]),
        "N115": int(tax_data["EARNED INCOME CREDIT PER COMPUTER"]),
        "N116": int(tax_data["SCHEDULE 8812 NONTAXABLE COMBAT PAY"]),
        "N117": int(tax_data["SCHEDULE 8812 ADDITIONAL CHILD TAX CREDIT PER COMPUTER"]),
        "N118": int(tax_data["REFUNDABLE EDUCATION CREDIT PER COMPUTER"]),
        "N119": int(tax_data["TOTAL NET EARNINGS PER COMPUTER"]),
        "N120": int(tax_data["TOTAL ITEMIZED DEDUCTIONS PER COMPUTER"]),
        "N121": int(tax_data["FORM 3800 GENERAL BUSINESS CREDITS PER COMPUTER"]),
        "N122": int(tax_data["PRIOR YR MIN TAX CREDIT"]),
        "N123": int(tax_data["ADOPTION CREDIT PER COMPUTER"]),
        "N124": int(tax_data["CREDIT FOR ELDERLY AND DISABLED PER COMPUTER"]),
        "N125": int(tax_data["F8910 ALTERNATIVE MOTOR VEHICLE CREDIT PER COMPUTER"]),
        "N126": int(tax_data["F8936 ELECTRIC MOTOR VEHICLE CREDIT PER COMPUTER"]),
        "N127": int(tax_data["FORM 8396 MORTGAGE CERTIFICATE CREDIT PER COMPUTER"]),
        "N128": int(tax_data["FORM 4136 CREDIT FOR FEDERAL TAX ON FUELS PER COMPUTER"]),
        "N129": int(tax_data["FORM 2439 REGULATED INVESTMENT COMPANY CREDIT"]),
        "N130": int(tax_data["REFUNDABLE CHILD CARE CREDIT"]),
    }

    return variables


def get_tax_variables_2020(tax_data):

    variables = {
        "M53": int(tax_data["SE INCOME PER COMPUTER"]),
        "M119": int(tax_data["TOTAL NET EARNINGS PER COMPUTER"])
    }

    return variables

def get_intake_data(intake_data):

    variables = {
        "T36": int(intake_data["Child_April_1_2020_through_December_31_2020"]),
        "T38": int(intake_data["Child_January_1_2021_through_March_31_2021"]),
        "T39": int(intake_data["Gov_April_1_2021_through_September_30_2021"]),
        "T40": int(intake_data["Gov_January_1_2021_through_March_31_2021"]),
        "T41": int(intake_data["Gov_April_1_2020_through_December_31_2020"]),
        "T42": int(intake_data["Family_January_1_2021_through_March_31_2021"]),
        "T43": int(intake_data["Family_April_1_2020_through_December_31_2020"]),
        "T44": int(intake_data["Child_April_1_2021_through_September_30_2021"]),
        "T45": int(intake_data["Family_April_1_2021_through_September_30_2021"])
    }

    return variables
