def get_tax_variables_2021(tax_data):
    variables = {
        "N37": tax_data["F8995 QUALIFIED BUSINESS INCOME DEDUCTION COMPUTER"],
        "N38": tax_data["SELF EMPLOYMENT TAX DEDUCTION PER COMPUTER"],
        "N39": tax_data["ADJUSTED GROSS INCOME"],
        "N40": tax_data["ADJUSTED GROSS INCOME PER COMPUTER"],
        "N41": tax_data["STANDARD DEDUCTION PER COMPUTER"],
        "N42": tax_data["TENTATIVE TAX"],
        "N43": tax_data["TOTAL CREDITS"],
        "N44": tax_data["SE TAX"],
        "N45": tax_data["FEDERAL INCOME TAX WITHHELD"],
        "N46": tax_data["ESTIMATED TAX PAYMENTS"],
        "N47": tax_data["OTHER PAYMENT CREDIT"],
        "N48": tax_data["EARNED INCOME CREDIT"],
        "N49": tax_data["TOTAL PAYMENTS"],
        "N50": tax_data["BAL DUE/OVER PYMT USING TP FIG PER COMPUTER"],
        "N51": tax_data["TOTAL QUALIFIED BUSINESS INCOME OR LOSS"],
        "N52": tax_data["FILING STATUS"],
        "N53": tax_data["SE INCOME PER COMPUTER"],
        "N54": tax_data["Credit to your account"], 
        "N55": tax_data["ACCOUNT BALANCE"],
        "N56": tax_data["ACCRUED INTEREST"],
        "N57": tax_data["TAXABLE INCOME"],
        "N58": tax_data["TAX PER RETURN"],
        "N59": tax_data["SCHEDULE 8812 ADDITIONAL CHILD TAX CREDIT"],
        "N60": tax_data["FORM 2439 REGULATED INVESTMENT COMPANY CREDIT1"],
        "N61": tax_data["FORM 4136 CREDIT FOR FEDERAL TAX ON FUELS PER COMPUTER1"],
        "N62": tax_data["TOTAL EDUCATION CREDIT AMOUNT PER COMPUTER"],
        "N63": tax_data["HEALTH COVERAGE TX CR"],
        "N64": tax_data["AMOUNT YOU OWE"],
        "N65": tax_data["REFUND AMOUNT"],
        "N66": tax_data["SICK FAMILY LEAVE CREDIT AFTER 3-31-21"],
        "N67": tax_data["SICK FAMILY LEAVE CREDIT"],
        "N68": tax_data["PREMIUM TAX CREDIT AMOUNT"],
        "N69": tax_data["REFUNDABLE CREDITS PER COMPUTER"],
        "N70": tax_data["SCHEDULE 8812 ADDITIONAL CHILD TAX CREDIT PER COMPUTER1"],
        "N71": tax_data["RECOVERY REBATE CREDIT PER COMPUTER"],
        "N72": tax_data["WAGES, SALARIES, TIPS, ETC"],
        "N73": tax_data["TAX-EXEMPT INTEREST"],
        "N74": tax_data["QUALIFIED DIVIDENDS"],
        "N75": tax_data["TOTAL IRA DISTRIBUTIONS"],
        "N76": tax_data["TOTAL PENSIONS AND ANNUITIES"],
        "N77": tax_data["TOTAL SOCIAL SECURITY BENEFITS"],
        "N78": tax_data["TAXABLE INTEREST INCOME"],
        "N79": tax_data["ORDINARY DIVIDEND INCOME"],
        "N80": tax_data["TAXABLE IRA DISTRIBUTIONS"],
        "N81": tax_data["TAXABLE PENSION/ANNUITY AMOUNT"],
        "N82": tax_data["TAXABLE SOCIAL SECURITY BENEFITS PER COMPUTER"],
        "N83": tax_data["CAPITAL GAIN OR LOSS"],
        "N84": tax_data["OTHER INCOME"],
        "N85": tax_data["TOTAL ADJUSTMENTS PER COMPUTER"],
        "N86": tax_data["NON ITEMIZED CHARITABLE CONTRIBUTION PER COMPUTER"],
        "N87": tax_data["BUSINESS INCOME OR LOSS (SCHEDULE C)"],
        "N88": tax_data["CHILD AND OTHER DEPENDENT CREDIT PER COMPUTER"],
        "N89": tax_data["EXCESS ADVANCE PREMIUM TAX CREDIT REPAYMENT AMOUNT"],
        "N90": tax_data["SEC 965 TAX INSTALLMENT"],
        "N91": tax_data["CHILD & DEPENDENT CARE CREDIT"],
        "N92": tax_data["ESTIMATED TAX PENALTY"],
        "N93": tax_data["APPLIED TO NEXT YEAR'S ESTIMATED TAX"],
        "N94": tax_data["EARNED INCOME CREDIT NONTAXABLE COMBAT PAY"],
        "N95": tax_data["MAX DEFERRED TAX PER COMPUTER"],
        "N96": tax_data["EIC PRIOR YEAR EARNED INCOME"],
        "N97": tax_data["FOREIGN TAX CREDIT PER COMPUTER"],
        "N98": tax_data["EDUCATION CREDIT PER COMPUTER"],
        "N99": tax_data["RETIREMENT SAVINGS CNTRB CREDIT PER COMPUTER"],
        "N100": tax_data["RESIDENTIAL CLEAN ENERGY CREDIT PER COMPUTER"],
        "N101": tax_data["F3800, F8801 AND OTHER CREDIT AMOUNT"],
        "N102": tax_data["AMOUNT PAID WITH FORM 4868"],
        "N103": tax_data["EXCESS SOCIAL SECURITY & RRTA TAX WITHHELD"],
        "N104": tax_data["ADDITIONAL INCOME PER COMPUTER"],
        "N105": tax_data["TOTAL INCOME PER COMPUTER"],
        "N106": tax_data["ADDITIONAL STANDARD DEDUCTION PER COMPUTER"],
        "N107": tax_data["TAXABLE INCOME PER COMPUTER"],
        "N108": tax_data["FORM 6251 ALTERNATIVE MINIMUM TAX PER COMPUTER"],
        "N109": tax_data["EXCESS ADVANCE PREMIUM TAX CREDIT REPAYMENT AMOUNT"],
        "N110": tax_data["TOTAL OTHER TAXES PER COMPUTER"],
        "N111": tax_data["TAXABLE INTEREST INCOME"],
        "N112": tax_data["ORDINARY DIVIDEND INCOME"],
        "N113": tax_data["CAPITAL GAINS OR LOSS"],
        "N114": tax_data["TENTATIVE TAX PER COMPUTER"],
        "N115": tax_data["EARNED INCOME CREDIT PER COMPUTER"],
        "N116": tax_data["SCHEDULE 8812 NONTAXABLE COMBAT PAY"],
        "N117": tax_data["SCHEDULE 8812 ADDITIONAL CHILD TAX CREDIT PER COMPUTER"],
        "N118": tax_data["REFUNDABLE EDUCATION CREDIT PER COMPUTER"],
        "N119": tax_data["TOTAL NET EARNINGS PER COMPUTER"],
        "N120": tax_data["TOTAL ITEMIZED DEDUCTIONS PER COMPUTER"],
        "N121": tax_data["FORM 3800 GENERAL BUSINESS CREDITS PER COMPUTER"],
        "N122": tax_data["PRIOR YR MIN TAX CREDIT"],
        "N123": tax_data["ADOPTION CREDIT PER COMPUTER"],
        "N124": tax_data["CREDIT FOR ELDERLY AND DISABLED PER COMPUTER"],
        "N125": tax_data["F8910 ALTERNATIVE MOTOR VEHICLE CREDIT PER COMPUTER"],
        "N126": tax_data["F8936 ELECTRIC MOTOR VEHICLE CREDIT PER COMPUTER"],
        "N127": tax_data["FORM 8396 MORTGAGE CERTIFICATE CREDIT PER COMPUTER"],
        "N128": tax_data["FORM 4136 CREDIT FOR FEDERAL TAX ON FUELS PER COMPUTER"],
        "N129": tax_data["FORM 2439 REGULATED INVESTMENT COMPANY CREDIT"],
        "N130": tax_data["REFUNDABLE CHILD CARE CREDIT"],
    }

    return variables

def get_tax_variables_2020(tax_data):

    variables = {
        "M53": tax_data["SE INCOME PER COMPUTER"],
        "M119": tax_data["TOTAL NET EARNINGS PER COMPUTER"]
    }

    return variables

def get_intake_data(intake_data):

    variables = {
        "T36": intake_data["Child_April_1_2020_through_December_31_2020"],
        "T38": intake_data["Child_January_1_2021_through_March_31_2021"],
        "T39": intake_data["Gov_April_1_2021_through_September_30_2021"],
        "T40": intake_data["Gov_January_1_2021_through_March_31_2021"],
        "T41": intake_data["Gov_April_1_2020_through_December_31_2020"],
        "T42": intake_data["Family_January_1_2021_through_March_31_2021"],
        "T43": intake_data["Family_April_1_2020_through_December_31_2020"],
        "T44": intake_data["Child_April_1_2021_through_September_30_2021"],
        "T45": intake_data["Family_April_1_2021_through_September_30_2021"]
    }

    return variables
